# .github/release.yml

changelog:
  categories:
    - title: 新增
      labels:
        - Git-Feat
    - title: 优化
      labels:
        - Git-Perf
    - title: 修复
      labels:
        - Git-Fix
    - title: 资源
      labels:
        - Git-Build
    - title: 文档
      labels:
        - Git-Docs
    - title: 其他
      labels:
        - "*"
